version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  rasa-chatbot:
    build: ./chatbot_prod
    ports:
      - "5005:5005"
    volumes:
      - ./chatbot_prod:/app
